[tool.poetry]
name = "super-rag"
version = "0.1.0"
description = ""
authors = ["Bastien98 <bastien.moenaert@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
