class Embeddings:
    def __init__(self, embeddings: list[list[float]]):
        self._embeddings = embeddings

    @property
    def embeddings(self) -> list[list[float]]:
        """The list of embeddings generated by the model."""
        return self._embeddings
